### ISSUE TITLE
cyclone

### ISSUE THREAD

**Issue by SIAS8848** [lucid-brndmg/cyclone-online-editor#1]
h

**Comment by lucid-brndmg** [comment]
Hi! Thanks for take a look at this project! 

I could take a look about your problem but my understandings of this language is pretty limited. I'm pretty familiar with the syntax and some of the semantics though. 

If you need assistance on writing Cyclone just send to my email haoyanglu2001#gmail.com and I could take a look. 
If you encounter problems using this editor please state the issue here. You may found an online url at:

https://fyp.cs.nuim.ie/projects/FYP24WH008

BTW I'm also a Chinese student currently at Maynooth, Ireland. Cheers.

**Comment by lucid-brndmg** [comment]
If you need tools or libs on performing syntactic analysis or semantic analysis on Cyclone source code, you may take a look at this project: https://github.com/lucid-brndmg/cyclone-analyzer

Sadly, the docs of that repo haven't been written yet since the frequent change on its API, and currently Im busy on other things. But eventually I will.

**Comment by SIAS8848** [comment]
Hello, I'm the student who just contacted you on github. That's right, I'm also a Chinese student of MU, haha. I had a problem learning cyclone, which is 2.8 on the tutorial, about McCarthy91 function.Do you have a reference answer to this there?&nbsp;I've written some code, but I've found that they don't work correctly.

Thanks for your time!




justin
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lucid-brndmg/cyclone-online-editor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月22日(星期五) 中午11:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lucid-brndmg/cyclone-online-editor] cyclone (Issue #1)





 
Hi! Thanks for take a look at this project!
 
I could take a look about your problem but my understandings of this language is pretty limited. I'm pretty familiar with the syntax and some of the semantics though.
 
If you need assistance on writing Cyclone just send to my email haoyanglu2001#gmail.com and I could take a look.
 If you encounter problems using this editor please state the issue here. You may found an online url at:
 
https://fyp.cs.nuim.ie/projects/FYP24WH008
 
BTW I'm also a Chinese student currently at Maynooth, Ireland. Cheers.
